theme = "dark_plus"

[editor]
line-number = "relative"
cursorline = true

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
D = "delete_char_backward"
"ret" = ["move_line_down", "goto_first_nonwhitespace"]

[keys.insert]
C-c = "normal_mode"

[keys.select]
C-c = "normal_mode"

[editor.whitespace.characters]
space = "·"
tab = "→"
