theme = "gruvbox"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
"semicolon" = "repeat_last_motion"

[keys.insert]
C-c = "normal_mode"

[keys.select]
C-c = "normal_mode"
