theme = "dark_plus"

[editor]
line-number = "relative"
cursorline = true
shell = ["zsh", "-c"]

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
D = "delete_char_backward"
"ret" = ["move_line_down", "goto_first_nonwhitespace"]
C-n = [
  "extend_line",
  ":insert-output echo 'FILL_THIS'",
  "extend_line_below",
  ":pipe sgpt --code --no-cache 'Using this comment, fill the line having the comment FILL_THIS.'",
]

[keys.insert]
C-c = "normal_mode"
C-n = [
  "normal_mode",
  "extend_line",
  ":insert-output echo 'FILL_THIS'",
  "extend_line_below",
  ":pipe sgpt --code --no-cache 'Using this comment, fill the line having the comment FILL_THIS.'",
]

[keys.select]
C-c = "normal_mode"

[editor.whitespace.characters]
space = "·"
tab = "→"
